<?php
namespace Database\Seeders;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;
use Carbon\Carbon;

class ProductSeeder extends Seeder
{
    public function run()
    {
        // 2. Sản phẩm
        DB::table('products')->insert([
            [
                'category_id' => 1,
                'name' => 'Áo thun nam cổ tròn',
                'slug' => Str::slug('Áo thun nam cổ tròn'),
                'price_products' => 199000,
                'status' => 1,
                'short_description' => 'Áo thun nam thoáng mát, dễ mặc.',
                'description' => 'Chất liệu cotton 100%, phù hợp cho mùa hè.',
                'thumbnail' => 'products/1.jpg',
            ],
            [
                'category_id' => 2,
                'name' => 'Áo kiểu nữ tay lỡ',
                'slug' => Str::slug('Áo kiểu nữ tay lỡ'),
                'price_products' => 249000,
                'status' => 1,
                'short_description' => 'Áo kiểu nữ thanh lịch.',
                'description' => 'Phù hợp đi làm hoặc đi chơi.',
                'thumbnail' => 'products/2.jpg',
            ],
            [
                'category_id' => 4,
                'name' => 'Đầm suông họa tiết hoa',
                'slug' => Str::slug('Đầm suông họa tiết hoa'),
                'price_products' => 300000,
                'status' => 1,
                'short_description' => 'Đầm suông nữ tính, nhẹ nhàng.',
                'description' => 'Vải voan thoáng mát, dễ chịu.',
                'thumbnail' => 'products/4.jpg',
            ],
            [
                'category_id' => 5,
                'name' => 'Bộ đồ thể thao Adidas',
                'slug' => Str::slug('Bộ đồ thể thao Adidas'),
                'price_products' => 99000,
                'status' => 1,
                'short_description' => 'Trang phục thể thao năng động.',
                'description' => 'Thích hợp tập luyện và vận động.',
                'thumbnail' => 'products/5.jpg',
            ],
            [
                'category_id' => 6,
                'name' => 'Bộ pijama lụa nữ',
                'slug' => Str::slug('Bộ pijama lụa nữ'),
                'price_products' => 20000,
                'status' => 1,
                'short_description' => 'Bộ đồ ngủ mềm mại, thoải mái.',
                'description' => 'Chất liệu lụa mềm mịn, cao cấp.',
                'thumbnail' => 'products/6.jpg',
            ],
            [
                'category_id' => 7,
                'name' => 'Đồ bơi một mảnh nữ',
                'slug' => Str::slug('Đồ bơi một mảnh nữ'),
                'price_products' => 150000,
                'status' => 1,
                'short_description' => 'Đồ bơi nữ thiết kế trẻ trung.',
                'description' => 'Phù hợp đi biển hoặc hồ bơi.',
                'thumbnail' => 'products/7.jpg',
            ],
            [
                'category_id' => 8,
                'name' => 'Áo sơ mi công sở nữ',
                'slug' => Str::slug('Áo sơ mi công sở nữ'),
                'price_products' => 250000,
                'status' => 1,
                'short_description' => 'Áo sơ mi trang nhã.',
                'description' => 'Thiết kế lịch sự, chuyên nghiệp.',
                'thumbnail' => 'products/8.jpg',
            ],
            [
                'category_id' => 9,
                'name' => 'Áo thun trẻ em',
                'slug' => Str::slug('Áo thun trẻ em'),
                'price_products' => 10000,
                'status' => 1,
                'short_description' => 'Áo cho bé trai, bé gái.',
                'description' => 'Chất liệu cotton, mềm nhẹ.',
                'thumbnail' => 'products/9.jpg',
            ],
            [
                'category_id' => 10,
                'name' => 'Áo khoác gió 2 lớp',
                'slug' => Str::slug('Áo khoác gió 2 lớp'),
                'price_products' => 120000,
                'status' => 1,
                'short_description' => 'Áo khoác chống gió, chống nước.',
                'description' => 'Phù hợp thời tiết chuyển mùa.',
                'thumbnail' => 'products/10.jpg',
            ],
            [
                'category_id' => 11,
                'name' => 'Quần jeans rách gối',
                'slug' => Str::slug('Quần jeans rách gối'),
                'price_products' => 150000,
                'status' => 1,
                'short_description' => 'Phong cách năng động, trẻ trung.',
                'description' => 'Form slimfit, chất liệu co giãn.',
                'thumbnail' => 'products/11.jpg',
            ],
            [
                'category_id' => 12,
                'name' => 'Áo sơ mi trắng dài tay',
                'slug' => Str::slug('Áo sơ mi trắng dài tay'),
                'price_products' => 290000,
                'status' => 1,
                'short_description' => 'Áo sơ mi cho mọi dịp.',
                'description' => 'Chất liệu kate, ít nhăn.',
                'thumbnail' => 'products/12.jpg',
            ],
            [
                'category_id' => 13,
                'name' => 'Áo thun basic trơn',
                'slug' => Str::slug('Áo thun basic trơn'),
                'price_products' => 149000,
                'status' => 1,
                'short_description' => 'Áo thun trơn, unisex.',
                'description' => 'Đa dạng màu sắc, dễ phối đồ.',
                'thumbnail' => 'products/13.jpg',
            ],
            [
                'category_id' => 14,
                'name' => 'Áo phao mùa đông có mũ',
                'slug' => Str::slug('Áo phao mùa đông có mũ'),
                'price_products' => 280000,
                'status' => 1,
                'short_description' => 'Giữ ấm cực tốt.',
                'description' => 'Thiết kế dày dặn, có mũ trùm.',
                'thumbnail' => 'products/14.jpg',
            ],
            [
                'category_id' => 15,
                'name' => 'Quần tây công sở nam',
                'slug' => Str::slug('Quần tây công sở nam'),
                'price_products' => 299000,
                'status' => 1,
                'short_description' => 'Form đứng, lịch sự.',
                'description' => 'Vải dày dặn, không nhăn.',
                'thumbnail' => 'products/15.jpg',
            ],
            [
                'category_id' => 16,
                'name' => 'Quần short jean nữ',
                'slug' => Str::slug('Quần short jean nữ'),
                'price_products' => 199000,
                'status' => 1,
                'short_description' => 'Thiết kế ngắn năng động.',
                'description' => 'Chất jean bền, đẹp.',
                'thumbnail' => 'products/16.jpg',
            ],
            [
                'category_id' => 17,
                'name' => 'Áo polo nam cổ bẻ',
                'slug' => Str::slug('Áo polo nam cổ bẻ'),
                'price_products' => 219000,
                'status' => 1,
                'short_description' => 'Phong cách trẻ trung.',
                'description' => 'Chất thun cá sấu thoáng mát.',
                'thumbnail' => 'products/17.jpg',
            ],
            [
                'category_id' => 18,
                'name' => 'Áo vest xám lịch lãm',
                'slug' => Str::slug('Áo vest xám lịch lãm'),
                'price_products' => 699000,
                'status' => 1,
                'short_description' => 'Lịch lãm và trang trọng.',
                'description' => 'Chất vải mịn, sang trọng.',
                'thumbnail' => 'products/18.jpg',
            ],
            [
                'category_id' => 19,
                'name' => 'Quần lót nam cotton',
                'slug' => Str::slug('Quần lót nam cotton'),
                'price_products' => 69000,
                'status' => 1,
                'short_description' => 'Chất liệu co giãn thoải mái.',
                'description' => 'Form ôm, thấm hút mồ hôi.',
                'thumbnail' => 'products/19.jpg',
            ],
            [
                'category_id' => 20,
                'name' => 'Áo lót ren nữ',
                'slug' => Str::slug('Áo lót ren nữ'),
                'price_products' => 89000,
                'status' => 1,
                'short_description' => 'Thiết kế tinh tế, gợi cảm.',
                'description' => 'Ren mềm, không gây kích ứng da.',
                'thumbnail' => 'products/20.jpg',
            ],
        ]);

    }
}
