<?php
namespace Database\Seeders;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;
use Carbon\Carbon;

class ProductSeeder extends Seeder
{
    public function run()
    {
        // 2. Sản phẩm
        DB::table('products')->insert([
            [
                'category_id' => 1,
                'name' => 'Áo thun nam cổ tròn',
                'slug' => Str::slug('Áo thun nam cổ tròn'),
                'price_products' => 199000,
                'status' => 1,
                'short_description' => 'Áo thun nam thoáng mát, dễ mặc.',
                'description' => 'Chất liệu cotton 100%, phù hợp cho mùa hè.',
                'thumbnail' => 'https://img.gkbcdn.com/s3/d/201810/880622ab-e708-4444-9475-82d77e418653.jpg',
            ],
            [
                'category_id' => 2,
                'name' => 'Áo kiểu nữ tay lỡ',
                'slug' => Str::slug('Áo kiểu nữ tay lỡ'),
                'price_products' => 249000,
                'status' => 1,
                'short_description' => 'Áo kiểu nữ thanh lịch.',
                'description' => 'Phù hợp đi làm hoặc đi chơi.',
                'thumbnail' => 'https://tse4.mm.bing.net/th/id/OIP.MxZzlokETjNTK1Yt8DsYYQHaHa?r=0&rs=1&pid=ImgDetMain&o=7&rm=3',
            ],
            [
                'category_id' => 3,
                'name' => 'Thắt lưng da bò',
                'slug' => Str::slug('Thắt lưng da bò'),
                'price_products' => 159000,
                'status' => 1,
                'short_description' => 'Thắt lưng da bền chắc.',
                'description' => 'Sản phẩm phụ kiện nam cao cấp.',
                'thumbnail' => 'https://tse1.mm.bing.net/th/id/OIP.Vwu1rE9ukmKqWeTCVaUhXAHaHa?r=0&rs=1&pid=ImgDetMain&o=7&rm=3',
            ],
            [
                'category_id' => 4,
                'name' => 'Đầm suông họa tiết hoa',
                'slug' => Str::slug('Đầm suông họa tiết hoa'),
                'price_products' => 399000,
                'status' => 1,
                'short_description' => 'Đầm suông nữ tính, nhẹ nhàng.',
                'description' => 'Vải voan thoáng mát, dễ chịu.',
                'thumbnail' => 'https://tse1.explicit.bing.net/th/id/OIP.w_MfXzG_tEzqYw0b-ryZuAHaO7?r=0&w=1080&h=2177&rs=1&pid=ImgDetMain&o=7&rm=3',
            ],
            [
                'category_id' => 5,
                'name' => 'Bộ đồ thể thao Adidas',
                'slug' => Str::slug('Bộ đồ thể thao Adidas'),
                'price_products' => 499000,
                'status' => 1,
                'short_description' => 'Trang phục thể thao năng động.',
                'description' => 'Thích hợp tập luyện và vận động.',
                'thumbnail' => 'https://cdn.vuahanghieu.com/unsafe/0x900/left/top/smart/filters:quality(90)/https://admin.vuahanghieu.com/upload/product/2021/09/6142ad04bb316-16092021093340.jpg',
            ],
            [
                'category_id' => 6,
                'name' => 'Bộ pijama lụa nữ',
                'slug' => Str::slug('Bộ pijama lụa nữ'),
                'price_products' => 299000,
                'status' => 1,
                'short_description' => 'Bộ đồ ngủ mềm mại, thoải mái.',
                'description' => 'Chất liệu lụa mềm mịn, cao cấp.',
                'thumbnail' => 'https://down-vn.img.susercontent.com/file/vn-11134207-7qukw-lf6csnx560ei03',
            ],
            [
                'category_id' => 7,
                'name' => 'Đồ bơi một mảnh nữ',
                'slug' => Str::slug('Đồ bơi một mảnh nữ'),
                'price_products' => 350000,
                'status' => 1,
                'short_description' => 'Đồ bơi nữ thiết kế trẻ trung.',
                'description' => 'Phù hợp đi biển hoặc hồ bơi.',
                'thumbnail' => 'https://tse3.mm.bing.net/th/id/OIP.n-W3Pj5SGzB9seMTcR77pgHaHa?r=0&rs=1&pid=ImgDetMain&o=7&rm=3',
            ],
            [
                'category_id' => 8,
                'name' => 'Áo sơ mi công sở nữ',
                'slug' => Str::slug('Áo sơ mi công sở nữ'),
                'price_products' => 270000,
                'status' => 1,
                'short_description' => 'Áo sơ mi trang nhã.',
                'description' => 'Thiết kế lịch sự, chuyên nghiệp.',
                'thumbnail' => 'products/so-mi-cong-so-nu.jpg',
            ],
            [
                'category_id' => 9,
                'name' => 'Áo thun trẻ em',
                'slug' => Str::slug('Áo thun trẻ em'),
                'price_products' => 99000,
                'status' => 1,
                'short_description' => 'Áo cho bé trai, bé gái.',
                'description' => 'Chất liệu cotton, mềm nhẹ.',
                'thumbnail' => 'products/ao-thun-tre-em.jpg',
            ],
            [
                'category_id' => 10,
                'name' => 'Áo khoác gió 2 lớp',
                'slug' => Str::slug('Áo khoác gió 2 lớp'),
                'price_products' => 320000,
                'status' => 1,
                'short_description' => 'Áo khoác chống gió, chống nước.',
                'description' => 'Phù hợp thời tiết chuyển mùa.',
                'thumbnail' => 'products/ao-khoac-gio-2-lop.jpg',
            ],
            [
                'category_id' => 11,
                'name' => 'Quần jeans rách gối',
                'slug' => Str::slug('Quần jeans rách gối'),
                'price_products' => 350000,
                'status' => 1,
                'short_description' => 'Phong cách năng động, trẻ trung.',
                'description' => 'Form slimfit, chất liệu co giãn.',
                'thumbnail' => 'products/quan-jeans-rach.jpg',
            ],
            [
                'category_id' => 12,
                'name' => 'Áo sơ mi trắng dài tay',
                'slug' => Str::slug('Áo sơ mi trắng dài tay'),
                'price_products' => 289000,
                'status' => 1,
                'short_description' => 'Áo sơ mi cho mọi dịp.',
                'description' => 'Chất liệu kate, ít nhăn.',
                'thumbnail' => 'products/so-mi-trang-dai-tay.jpg',
            ],
            [
                'category_id' => 13,
                'name' => 'Áo thun basic trơn',
                'slug' => Str::slug('Áo thun basic trơn'),
                'price_products' => 149000,
                'status' => 1,
                'short_description' => 'Áo thun trơn, unisex.',
                'description' => 'Đa dạng màu sắc, dễ phối đồ.',
                'thumbnail' => 'products/ao-thun-basic.jpg',
            ],
            [
                'category_id' => 14,
                'name' => 'Áo phao mùa đông có mũ',
                'slug' => Str::slug('Áo phao mùa đông có mũ'),
                'price_products' => 480000,
                'status' => 1,
                'short_description' => 'Giữ ấm cực tốt.',
                'description' => 'Thiết kế dày dặn, có mũ trùm.',
                'thumbnail' => 'products/ao-phao-mua-dong.jpg',
            ],
            [
                'category_id' => 15,
                'name' => 'Quần tây công sở nam',
                'slug' => Str::slug('Quần tây công sở nam'),
                'price_products' => 299000,
                'status' => 1,
                'short_description' => 'Form đứng, lịch sự.',
                'description' => 'Vải dày dặn, không nhăn.',
                'thumbnail' => 'products/quan-tay-nam.jpg',
            ],
            [
                'category_id' => 16,
                'name' => 'Quần short jean nữ',
                'slug' => Str::slug('Quần short jean nữ'),
                'price_products' => 199000,
                'status' => 1,
                'short_description' => 'Thiết kế ngắn năng động.',
                'description' => 'Chất jean bền, đẹp.',
                'thumbnail' => 'products/quan-short-nu.jpg',
            ],
            [
                'category_id' => 17,
                'name' => 'Áo polo nam cổ bẻ',
                'slug' => Str::slug('Áo polo nam cổ bẻ'),
                'price_products' => 219000,
                'status' => 1,
                'short_description' => 'Phong cách trẻ trung.',
                'description' => 'Chất thun cá sấu thoáng mát.',
                'thumbnail' => 'products/ao-polo-nam.jpg',
            ],
            [
                'category_id' => 18,
                'name' => 'Áo vest xám lịch lãm',
                'slug' => Str::slug('Áo vest xám lịch lãm'),
                'price_products' => 699000,
                'status' => 1,
                'short_description' => 'Lịch lãm và trang trọng.',
                'description' => 'Chất vải mịn, sang trọng.',
                'thumbnail' => 'products/ao-vest-xam.jpg',
            ],
            [
                'category_id' => 19,
                'name' => 'Quần lót nam cotton',
                'slug' => Str::slug('Quần lót nam cotton'),
                'price_products' => 69000,
                'status' => 1,
                'short_description' => 'Chất liệu co giãn thoải mái.',
                'description' => 'Form ôm, thấm hút mồ hôi.',
                'thumbnail' => 'products/quan-lot-nam.jpg',
            ],
            [
                'category_id' => 20,
                'name' => 'Áo lót ren nữ',
                'slug' => Str::slug('Áo lót ren nữ'),
                'price_products' => 89000,
                'status' => 1,
                'short_description' => 'Thiết kế tinh tế, gợi cảm.',
                'description' => 'Ren mềm, không gây kích ứng da.',
                'thumbnail' => 'products/ao-lot-ren-nu.jpg',
            ],
        ]);

    }
}
